FROM maven:3.5-jdk-8-alpine as builder
COPY ./../../webapp/src /usr/src/app/src
COPY ./../../webapp/pom.xml /usr/src/app/src/pom.xml
COPY ./../../pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean install
RUN ls /usr/src/app/target/*

FROM httpd
ENV Name "siddhesh Dike"
WORKDIR /var/www/html
RUN echo ${Name} > index.html
EXPOSE 80
CMD ["httpd-foreground"]